#!/bin/sh

set -o errexit

set -o nounset


worker_ready(){
    celery -A backend inspect ping
}

until worker_ready; do
    >&2 echo 'Celery workers not available :-('
    sleep 1

done
>&2 echo 'Celery workers are available and ready!!!'

celery -A backend flower \
    --port=5555 \
    --broker="${CELERY_BROKER}"