# Generated by Django 5.1.3 on 2025-05-12 15:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "primary_key_id",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "plan",
                    models.CharField(
                        choices=[
                            ("Basic", "Basic"),
                            ("Pro", "Pro"),
                            ("Elite", "Elite"),
                        ],
                        default="Pro",
                        max_length=10,
                        verbose_name="Plan",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        editable=False,
                        max_digits=6,
                        verbose_name="Price",
                    ),
                ),
                (
                    "start_date",
                    models.DateTimeField(auto_now_add=True, verbose_name="Start Date"),
                ),
                (
                    "end_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="End Date"
                    ),
                ),
                ("is_trial", models.BooleanField(default=False)),
                ("active", models.BooleanField(default=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscription",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
